FROM python:3.7-slim-stretch

RUN apt-get update && apt-get install -y git python3-dev gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install --upgrade -r requirements.txt

EXPOSE 5000

CMD ["bash"]

# docker build --rm=true -t gpr .
# docker run --rm -p 5000:5000/tcp gpr:latest
# docker run --name gpr -it -p 5000:5000/tcp -v /Users/user/3xs/Dropbox/notebooks/gpr/fastai-gpr-app:/gpr gpr:latest 